movie-CBV/app/urls.py
from django.contrib import admin
from django.urls import path
from app import views
app_name='app'

urlpatterns = [
    # path('', views.home,name='home'),
    path('',views.Movielist.as_view(),name='home'),

    # path('one/<str:p>',views.one,name='one'),
    path('one/<pk>',views.Movieview.as_view(),name='one'),      # pk --> primary key

    # path('add',views.add,name='add'),
    path('add',views.Movieadd.as_view(),name='add'),

    # path('edit/<str:p>',views.edit,name='edit'),
    path('edit/<pk>',views.Movieupdate.as_view(),name='edit'),


    # path('delete/<str:p>',views.delete,name='delete'),
    path('delete/<pk>',views.Moviedelete.as_view(),name='delete'),

]

movie-CBV/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls"))
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie-CBV/app/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name=models.CharField(max_length=20,unique=True,primary_key=True)
    desc=models.CharField(max_length=300)
    year=models.IntegerField()
    image=models.ImageField(upload_to="movies/image",null=True,blank=True)

    def __str__(self):
        return self.name

movie-CBV/app/forms.py
from django import forms
from app.models import Movie

class movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields="__all__"

movie-CBV/app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from app.models import Movie
from app.forms import movieform
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
# def home(request):
#     m=Movie.objects.all()
#     return render(request,'home.html',{'movie_list':m})

class Movielist(ListView):      #ListView displays all objects/records retrieving from a model.
    model=Movie
    template_name = "home.html"
    context_object_name = "movie_list"


# def one(request,p):                                     #view specific movie details
#     b=Movie.objects.get(name=p)
#     return render(request,'1.html',{'b':b})

class Movieview(DetailView):    # DetailView displays a particular object retrieving from a model.
    model = Movie
    template_name = '1.html'
    context_object_name = 'b'

# def add(request):
#     if (request.method=="POST"):
#         form=movieform(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#             return home(request)
#     form=movieform()
#     return render(request,'add.html',{'form':form})

class Movieadd(CreateView):
    model=Movie
    template_name = 'add.html'
    fields = '__all__'
    success_url = reverse_lazy('app:home')

# def edit(request,p):
#     b=Movie.objects.get(name=p)
#     if(request.method=="POST"):
#         form=movieform(request.POST,request.FILES,instance=b)
#         if form.is_valid():
#             form.save()
#             return home(request)
#     else:
#         form=movieform(instance=b)
#         return render(request,'edit.html',{'form':form})

class Movieupdate(UpdateView):
    model = Movie
    template_name = 'edit.html'
    fields = '__all__'
    success_url = reverse_lazy('app:home')

# def delete(request,p):
#     b=Movie.objects.get(name=p)
#     b.delete()
#     return home(request)

class Moviedelete(DeleteView):
    model = Movie
    template_name = 'delete.html'
    success_url = reverse_lazy('app:home')

movie-CBV/templates/1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="text-white">
    <div>
    <img src="{{b.image.url}}" height="350px" width="300px">
    </div>
</div>
    <div id="position2">
        <h3>{{b.name}}</h3><br>
        <div style="height:120px; width:300px;">
        <p>{{b.desc}}</p>
        <h6>Release year: {{b.year}}</h6>
        </div><br><br>
        <a class="btn btn-warning me-2" href="{% url 'app:edit' b.name %}" role="button">Update
        <a class="btn btn-danger" href="{% url 'app:delete' b.name %}" role="button">Delete</a>
<!--        <button type="button" class="btn btn-warning">Update</button>-->
<!--        <button type="button" class="btn btn-danger">Delete</button>-->


    </div>

{% endblock %}

movie-CBV/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<h3>Add new movie</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

        {{form|crispy}}

    <br>
    <input class="bg-light" type="submit">
</form>

{% endblock %}

movie-CBV/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ONLINE MOVIE STORE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <form class="d-flex" method="POST">
          {% csrf_token %}
        <a class="btn btn-primary" href="{% url 'app:add' %}" role="button">ADD</a>
      </form>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie-CBV/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete?</p>
    <input type="submit">
</form>
{% endblock %}

movie-CBV/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>Edit movie details</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit">
</form>
{% endblock %}

movie-CBV/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
<div class="row" >
    {% for i in movie_list %}
    <div class="col-sm-3">
        <div class="card" style="height:110vh; width: 18rem;">
            <img src="{{i.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <p class="card-text">{{i.desc}}</p>
                <a href="{% url 'app:one' i.name %}" class="btn btn-primary">View {{i.name}} details</a>
            </div>
        </div>
    </div>
{% endfor %}
</div>
</div>

{% endblock %}